export function authPage(register = false, error = ''): Response {
  const title = register ? 'Create your account' : 'Sign in'
  // Error messages are fixed server-owned text, never interpolated user input.
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · StackDues</title><style>body{margin:0;background:#f6f4ed;color:#27342d;font:16px system-ui;display:grid;min-height:100vh;place-items:center}main{box-sizing:border-box;width:min(100%,430px);padding:32px}h1{font:36px Georgia}label{display:block;margin:20px 0 6px}input,button{box-sizing:border-box;width:100%;padding:12px;font:inherit;border:1px solid #a7aaa1;border-radius:5px}button{margin-top:24px;background:#a64c32;color:white;cursor:pointer}a{color:#8c402b}p{line-height:1.6}small{display:block;margin-top:6px;color:#59645c}.error{color:#9f3d20}</style></head><body><main><p>StackDues · Personal workspace</p><h1>${title}</h1>${error ? `<p class="error" role="alert">${error}</p>` : ''}<form method="post" action="/auth/${register ? 'register' : 'login'}"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="username" required maxlength="254"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="${register ? 'new-password' : 'current-password'}" required minlength="16" maxlength="1024">${register ? '<small>Use at least 16 characters. A password manager can generate one.</small><label for="code">One-time setup code</label><input id="code" name="code" type="password" autocomplete="off" required maxlength="128"><small>The workspace owner has the setup code. Account creation is available once.</small>' : ''}<button type="submit">${title}</button></form><p>${register ? '<a href="/login">Already have an account? Sign in</a>' : '<a href="/register">Create your owner account</a>'}</p></main></body></html>`
  return new Response(html, { headers: {
    'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store',
    'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'",
    'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer',
  } })
}
